version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: '[%(levelname)s][%(asctime)s][%(filename)s:%(funcName)s:%(lineno)d] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  json:
    format: '{"level": "%(levelname)s", "time": "%(asctime)s", "file": "%(filename)s", "function": "%(funcName)s", "line": %(lineno)d, "message": "%(message)s"}'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: ext://sys.stdout

  rotating_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: '/tmp/dev_app_logs.log'
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: 'utf-8'

  json_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: '/tmp/dev_app_logs.json'
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: 'utf-8'

loggers:
  fastapi:
    level: DEBUG
    handlers: [console]
    propagate: no

  websocket:
    level: DEBUG
    handlers: [console]
    propagate: no

  database:
    level: DEBUG
    handlers: [console]
    propagate: no
