version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_DB: narae
      POSTGRES_USER: narae
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_user_password
      PGDATA: /data/postgres
    volumes:
      - pg_data:/data/postgres
    networks:
      - narae-network
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'narae']
      interval: 30s
      timeout: 10s
      retries: 5
    secrets:
      - postgres_user_password

  # adminer:
  #   image: adminer:4.8.1-standalone
  #   restart: always
  #   environment:
  #     ADMINER_DEFAULT_SERVER: postgres
  #     ADMINER_DESIGN: pepa-linha-dark
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres
  #   networks:
  #     - narae-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.5
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: dury.ko@gmail.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/postgres_user_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pg_admin:/var/lib/pgadmin
    ports:
      - 8080:80
    networks:
      - narae-network
    secrets:
      - postgres_user_password

volumes:
  pg_data:
  pg_admin:

networks:
  narae-network:
    external: true

secrets:
  postgres_user_password:
    file: ./secrets/pg_user_password.txt
