version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=/var/lib/mysql-files
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: narae
      MYSQL_USER: narae
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    volumes:
      - db_data:/var/lib/mysql
      - db_backup:/var/lib/mysql-files
    networks:
      - narae-network
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    secrets:
      - mysql_root_password
      - mysql_user_password

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: pepa-linha-dark
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - narae-network

volumes:
  db_data:
  db_backup:

networks:
  narae-network:
    external: true

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_user_password:
    file: ./secrets/mysql_user_password.txt
