"""Update action model feedback column

Revision ID: 0a6a657f3788
Revises: 8d80fa84c250
Create Date: 2024-06-13 22:09:03.551751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6a657f3788'
down_revision: Union[str, None] = '8d80fa84c250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Action', sa.Column('feedback', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Action', 'feedback')
    # ### end Alembic commands ###
