"""Create limit table

Revision ID: 2a157aba3acc
Revises: c0100b49f8ab
Create Date: 2024-05-07 06:20:01.971173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a157aba3acc'
down_revision: Union[str, None] = 'c0100b49f8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Limit',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Limit_user_id_to_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Limit'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Limit')
    # ### end Alembic commands ###
