"""Create mentor v2 table

Revision ID: 2bd2af38b89e
Revises: 2a157aba3acc
Create Date: 2024-05-07 10:48:42.125708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd2af38b89e'
down_revision: Union[str, None] = '2a157aba3acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Mentor2',
    sa.Column('mentor_name', sa.String(length=45), nullable=False),
    sa.Column('mentor_field', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('situation', sa.String(length=256), nullable=False),
    sa.Column('task', sa.String(length=256), nullable=False),
    sa.Column('intent', sa.String(length=256), nullable=False),
    sa.Column('concern', sa.String(length=256), nullable=False),
    sa.Column('calibrate', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Mentor2_user_id_to_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Mentor2'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Mentor2')
    # ### end Alembic commands ###
