"""Update mentor v2 to support curriculum and action

Revision ID: 4aad2030d4c4
Revises: 0079f91f0887
Create Date: 2024-06-10 04:49:13.367515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aad2030d4c4'
down_revision: Union[str, None] = '0079f91f0887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Action',
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['Mentor2.id'], name=op.f('fk_Action_mentor_id_to_Mentor2')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Action'))
    )
    op.add_column('Mentor2', sa.Column('curriculum', sa.Text(), nullable=True))
    op.add_column('Mentor2', sa.Column('curriculum_phase', sa.Text(), nullable=True))
    op.add_column('Mentor2', sa.Column('action_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_Mentor2_action_id_to_Action'), 'Mentor2', 'Action', ['action_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Mentor2_action_id_to_Action'), 'Mentor2', type_='foreignkey')
    op.drop_column('Mentor2', 'action_id')
    op.drop_column('Mentor2', 'curriculum_phase')
    op.drop_column('Mentor2', 'curriculum')
    op.drop_table('Action')
    # ### end Alembic commands ###
