"""Update mentor v2 to support curriculum and action

Revision ID: 4d933745539b
Revises: 0079f91f0887
Create Date: 2024-06-13 00:39:50.538105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d933745539b'
down_revision: Union[str, None] = '0079f91f0887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Action',
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['Mentor2.id'], name=op.f('fk_Action_mentor_id_to_Mentor2')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Action'))
    )
    op.drop_index('ix_Mentor_Mentor_id', table_name='Mentor')
    op.drop_table('Mentor')
    op.add_column('Mentor2', sa.Column('curriculum', sa.Text(), nullable=True))
    op.add_column('Mentor2', sa.Column('curriculum_phase', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Mentor2', 'curriculum_phase')
    op.drop_column('Mentor2', 'curriculum')
    op.create_table('Mentor',
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('mentor_name', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('mentor_field', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('situation', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('task', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('intent', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('concern', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('calibrate', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_Mentor'),
    sa.UniqueConstraint('mentor_name', name='uq_Mentor_mentor_name')
    )
    op.create_index('ix_Mentor_Mentor_id', 'Mentor', ['id'], unique=False)
    op.drop_table('Action')
    # ### end Alembic commands ###
