"""Create FeedbackTable

Revision ID: 5641c721f0b3
Revises: 6c7dd55ef000
Create Date: 2024-05-19 11:12:13.124648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5641c721f0b3'
down_revision: Union[str, None] = '6c7dd55ef000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Feedback',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['Mentor2.id'], name=op.f('fk_Feedback_mentor_id_to_Mentor2')),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Feedback_user_id_to_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Feedback'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Feedback')
    # ### end Alembic commands ###
