"""Create ChatHistoryTable

Revision ID: 6146d65ec9fb
Revises: 2bd2af38b89e
Create Date: 2024-05-16 17:42:40.883055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6146d65ec9fb'
down_revision: Union[str, None] = '2bd2af38b89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ChatHistory',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('chat_data', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['Mentor2.id'], name=op.f('fk_ChatHistory_mentor_id_to_Mentor2')),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_ChatHistory_user_id_to_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ChatHistory'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ChatHistory')
    # ### end Alembic commands ###
