"""Create document chunk table

Revision ID: 7e95df1558d9
Revises: c30c4d7c367d
Create Date: 2024-06-21 04:45:27.369591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision: str = '7e95df1558d9'
down_revision: Union[str, None] = 'c30c4d7c367d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentchunk',
    sa.Column('field', sa.Integer(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documentchunk'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentchunk')
    # ### end Alembic commands ###
