""" chatting seq

Revision ID: 9f4e077c2595
Revises: 0a6a657f3788
Create Date: 2024-06-14 06:23:09.620406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4e077c2595'
down_revision: Union[str, None] = '0a6a657f3788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ChatHistory', 'seq')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ChatHistory', sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
