"""Create user, mentor, item tables

Revision ID: c0100b49f8ab
Revises: d9aed0987f04
Create Date: 2024-05-07 05:24:11.116644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0100b49f8ab'
down_revision: Union[str, None] = 'd9aed0987f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Mentor',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('mentor_name', sa.String(length=45), nullable=False),
    sa.Column('mentor_field', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('situation', sa.String(length=256), nullable=False),
    sa.Column('task', sa.String(length=256), nullable=False),
    sa.Column('intent', sa.String(length=256), nullable=False),
    sa.Column('concern', sa.String(length=256), nullable=False),
    sa.Column('calibrate', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Mentor')),
    sa.UniqueConstraint('mentor_name', name=op.f('uq_Mentor_mentor_name'))
    )
    op.create_index(op.f('ix_Mentor_Mentor_id'), 'Mentor', ['id'], unique=False)
    op.create_table('User',
    sa.Column('email', sa.String(length=120), autoincrement=True, nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_User'))
    )
    op.create_index(op.f('ix_User_User_email'), 'User', ['email'], unique=True)
    op.create_table('item',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_index(op.f('ix_User_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Mentor_Mentor_id'), table_name='Mentor')
    op.drop_table('Mentor')
    # ### end Alembic commands ###
