"""Create vectorItem for test

Revision ID: c30c4d7c367d
Revises: 9cecb51a17b8
Create Date: 2024-06-21 02:56:33.157802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision: str = 'c30c4d7c367d'
down_revision: Union[str, None] = '9cecb51a17b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddingitem',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=3), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddingitem'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embeddingitem')
    # ### end Alembic commands ###
