name: Docker image build and push

on:
  push:
    branches: [ "main" ]
    paths: [ "app/**", "requirements.txt", ".dockerignore", "Dockerfile" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "app/**", "requirements.txt", ".dockerignore", "Dockerfile" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: codinggroot/narae:${{ env.TIMESTAMP }},codinggroot/narae:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
