name: Containerize

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "app/**", "requirements.txt", ".dockerignore", "Dockerfile" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "app/**", "requirements.txt", ".dockerignore", "Dockerfile" ]

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    name: Push docker image to DockerHub and AWS Registry
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::637423298185:role/github-actions-for-ecr-push
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login AWS Public ECR
      id: ecr
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u5h7r6e3
    - name: Get timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: codinggroot/narae:${{ env.TIMESTAMP }},codinggroot/narae:latest,public.ecr.aws/u5h7r6e3/narae:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
